version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: cat-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./cat-app-backend
    container_name: cat-backend
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/catapp
    volumes:
      - ./cat-app-backend:/usr/src/app
    command: npm run start:prod

  frontend:
    build:
      context: ./cat-app
    container_name: cat-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data:
